### ISSUE TITLE
Adding wizards to start talking :)

### ISSUE THREAD

**Issue by miguelpaz** [miguelpaz/normalista#3]
@jueyang meet @davo and viceversa. You both have already done a lot of work on normalista in different repos. Now that I merged Jue's pull request to master, you both can talk and come up with the best way you agree to continue forward. I know Davo has been working a lot on design too.

**Comment by davo** [comment]
Hi @miguelpaz... Hello @jueyang, nice to meet you... can you write me at davidgalavotti at gmail dot com, maybe we can get together on a Hangout / Skype call later today to know how match our efforts. I can show you what I've been designing :)

**Comment by davo** [comment]
Hey @miguelpaz we just finished the call with @jueyang!

Follow up for the next days:
- Run normalista via Jekyll on local (Davo)
- Update documentation with instructions to run local env (Jue)
- Build SCSS / SASS / Tachyons architecture (Jue & Davo)
- Build a template for the Homework template (Jue & Davo)
- Testing Homework template (Miguel, Jue, Davo, ask for friends)
- Build basic components based on Homework

Miguel, after reading this close this issue. I'll turn the ToDo into a series of issues.

Later!

**Comment by miguelpaz** [comment]
Done Davo.

**Comment by miguelpaz** [comment]
Done Davo.
